language: node_js
install: 
  - npm install grunt
  - bash ./first_run.sh
node_js:
  - 10.13
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.1.1
# before_script:
#   - bash ./first_run.sh
services: mongodb
script: 
  - grunt test
